Dave Dev/src/objects/Synced_Cell__c.object
<CustomObject>
    <description>By nominating a worksheet and cell reference, a user can sync data from workbook to sf, and sf back to workbook.</description>
    <fields>
        <fullName>Cell_Value__c</fullName>
        <inlineHelpText>To sync a cell you must describe its location exactly, in the format of [sheetname]![column reference]:[row reference] eg. cell A1 on &apos;Sheet 1&apos; would be entered as follows - Sheet 1!A:1</inlineHelpText>
        <label>Cell Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workbook__c</fullName>
        <label>Workbook</label>
        <referenceTo>Workbook__c</referenceTo>
        <relationshipLabel>Synced Cells</relationshipLabel>
        <relationshipName>Synced_Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>force_refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, forces trigger to refresh cell value</description>
        <label>force refresh</label>
        <type>Checkbox</type>
    </fields>
    <label>Synced Cell</label>
    <nameField>
        <label>Synced Cell</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Synced Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dave Dev/src/objects/Workbook__c.object
<CustomObject>
    <description>Saves a jQuery spreadsheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workbooks</relationshipLabel>
        <relationshipName>Workbooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WorkbookURL__c</fullName>
        <label>WorkbookURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Worksheets__c</fullName>
        <label>Worksheets</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Workbook</label>
    <nameField>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dave Dev/src/classes/workbookExtension.cls
public class workbookExtension {

    private final workbook__c wb {get;set;}
    public workbook__c newwb {
    get{
        if(newwb == null) newwb = new workbook__c();
        return newwb;
    }
    set;
    }
    
    public pagereference submit(){
        workbook__c cwb = [Select w.Worksheets__c, w.WorkbookURL__c, w.SystemModstamp, w.Name, w.LastModifiedDate, w.LastModifiedById, w.IsDeleted, w.Id, w.CreatedDate, w.CreatedById, w.Account__c, (Select Id, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, Cell_Value__c, Workbook__c, force_refresh__c From Synced_Cells__r) From Workbook__c w where w.id =:wb.id limit 1];
        workbook__c cwbCopy = cwb.clone(false,true,false,false);
        cwbCopy.account__c = newwb.account__c;
        cwbCopy.name = 'Copy of '+cwb.name;
        cwbCopy.WorkbookURL__c = 'https://c.ap1.visual.force.com/apex/sheet_test?aid='+newwb.account__c;
        insert cwbCopy;
        cwbCopy.WorkbookURL__c += '&wid='+cwbCopy.id;
        update cwbCopy;
        
        // copy over synced cells
        syncedCellUtility.disableCellTrigger = true;
        List<synced_cell__c> scList = new List<synced_cell__c>();
        for(synced_cell__c sc : cwb.synced_cells__r){
            synced_cell__c stmp = sc.clone(false,true,false,false);
            stmp.workbook__c = cwbCopy.id;
            scList.add(stmp);
        }
        if(!scList.isEmpty()) insert scList;
        
        syncedCellUtility.disableCellTrigger = false;
        
        // copy over the data attachment
        attachment att = [Select a.SystemModstamp, a.ParentId, a.OwnerId, a.Name, a.LastModifiedDate, a.LastModifiedById, a.IsPrivate, a.IsDeleted, a.Id, a.Description, a.CreatedDate, a.CreatedById, a.ContentType, a.BodyLength, a.Body From Attachment a where ParentId =:cwb.id limit 1];
        attachment atmp = att.clone(false,true,false,false);
        atmp.ParentId = cwbCopy.id;
        insert atmp;
        
        Pagereference pr = new PageReference('/'+cwbCopy.id);
        pr.setRedirect(true);
        return pr;
    }
    
    public workbookExtension(ApexPages.StandardController controller) {
        this.wb = (workbook__c)controller.getRecord();
    }

}